import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { ThemeProvider } from 'next-themes';
import { Toaster } from '@/components/ui/sonner';
import { AuthProvider } from '@/context/AuthContext';
import { BoardsProvider } from '@/context/BoardContext';

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: '--font-jakarta',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Kanban',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn('h-full', 'antialiased', plusJakartaSans.variable)}
      suppressHydrationWarning
    >
      <body className="min-h-screen min-h-dvh flex flex-col bg-background">
        <ThemeProvider defaultTheme="dark">
          <Toaster position="top-right" />
          <AuthProvider>
            <BoardsProvider>{children}</BoardsProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
